repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: "master"
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
-   repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
    -   id: black